### ISSUE TITLE
Dataset ib6v13 (WFC3 11677_13) crashes MVM pipeline

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1019]
_Issue [HLA-540](https://jira.stsci.edu/browse/HLA-540) was created on JIRA by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude):_

 
```
Traceback (most recent call last):
  File "/Users/dulude/Documents/Code/HLATransition/drizzlepac/drizzlepac/hapmultisequencer.py", line 235, in run_mvm_processing
    output_custom_pars_file=output_custom_pars_file)
  File "/Users/dulude/Documents/Code/HLATransition/drizzlepac/drizzlepac/haputils/config_utils.py", line 65, in __init__
    self._determine_conditions(prod_obj)
  File "/Users/dulude/Documents/Code/HLATransition/drizzlepac/drizzlepac/haputils/config_utils.py", line 115, in _determine_conditions
    n_exp = int(round(prod_obj.mask_kws['MEANNEXP'][0]))  # Use mean number of exposures in skycell instead of just simple number of input images for MVM
ValueError: cannot convert float NaN to integer
```

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-540?focusedCommentId=532458#comment-532458):_

Tickets HLA-541 and HLA-540 appear to be related. Tried running mvm pipeline with another dataset from the same skyframe (acs_12950_01 (jc2r01) and it displayed the same failure mode. I think it has something to do with this skyframe (p0046x02y17).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-540?focusedCommentId=535769#comment-535769):_

Issue resolved by [PR 1059](https://github.com/spacetelescope/drizzlepac/pull/1059)
