### ISSUE TITLE
Running dataset ib6v13 (WFC3 11677_13) through search_skyframes.py results in blank footprint images

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1020]
_Issue [HLA-541](https://jira.stsci.edu/browse/HLA-541) was created on JIRA by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude):_

* Execution of the script is otherwise as expected. The appropriate footprint .fits images are generated, but they are all blank. 
 * It is not known at this time if this behaviour is in any way related to ticket [HLA-540](https://jira.stsci.edu/browse/HLA-540).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-541?focusedCommentId=532629#comment-532629):_

Code crashes on HLALAB1 when attempting run to make footprint images of all exposures present in skycell p0046x02y17 from home directory: 
```java
(caldp_20201208) dulude@hlalab1 ~/skycell_test $ python ../drizzlepac/drizzlepac/devutils/search_skyframes.py -s p0046x02y17 --output_sorting config,spec -v
Query "skycell == 'p0046x02y17'" found 295 results.
Column sorting order: config, spec
Building footprint images. Please be patient. This may take some time...
Traceback (most recent call last):
  File "../drizzlepac/drizzlepac/devutils/search_skyframes.py", line 414, in <module>
    visualize_footprints(results)
  File "../drizzlepac/drizzlepac/devutils/search_skyframes.py", line 246, in visualize_footprints
    make_footprint_fits_file(skycell_name, img_list, footprint_imgname)
  File "../drizzlepac/drizzlepac/devutils/search_skyframes.py", line 277, in make_footprint_fits_file
    footprint.build(img_list)
  File "/home/dulude/drizzlepac/drizzlepac/haputils/cell_utils.py", line 290, in build
    blank = np.array(img).astype(np.int16)
MemoryError: Unable to allocate 875. MiB for an array with shape (21418, 21418) and data type int16
```
 

Not sure if this just a matter of running out of space or something else.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-541?focusedCommentId=535289#comment-535289):_

After speaking with Warren, blank skycells appear to be correct. The problem isn't that these skycells shouldn't be created. Rather, The correct WCS info is not being used during generation, resulting in blank footprint images.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-541?focusedCommentId=535770#comment-535770):_

Issue resolved by [PR 1059](https://github.com/spacetelescope/drizzlepac/pull/1059)
