### ISSUE TITLE
MVM failure: IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1358]
_Issue [HLA-764](https://jira.stsci.edu/browse/HLA-764) was created on JIRA by [Matthew Burger](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mburger):_

A few skycells have failed in MVM_Repro: 

skycell-p2489x15y02

skycell-p0544x18y15

skycell-p0081x16y13

Error message:

 
```java
Traceback (most recent call last):
  File "/dms/local/hst/pipeline/pkgs/miniconda3/envs/caldp_20220406/lib/python3.8/site-packages/drizzlepac/hapmultisequencer.py", line 375, in run_mvm_processing
    filter_item.generate_footprint_mask(save_mask=False)
  File "/dms/local/hst/pipeline/pkgs/miniconda3/envs/caldp_20220406/lib/python3.8/site-packages/drizzlepac/haputils/product.py", line 105, in generate_footprint_mask
    footprint.build(exposure_names, scale=True)
  File "/dms/local/hst/pipeline/pkgs/miniconda3/envs/caldp_20220406/lib/python3.8/site-packages/drizzlepac/haputils/cell_utils.py", line 381, in build
    self.find_bounded_wcs()
  File "/dms/local/hst/pipeline/pkgs/miniconda3/envs/caldp_20220406/lib/python3.8/site-packages/drizzlepac/haputils/cell_utils.py", line 430, in find_bounded_wcs
    ymin, ymax, xmin, xmax = calc_bounding_box(self.total_mask)
  File "/dms/local/hst/pipeline/pkgs/miniconda3/envs/caldp_20220406/lib/python3.8/site-packages/drizzlepac/haputils/cell_utils.py", line 1135, in calc_bounding_box
    rmin, rmax = np.where(rows)[0][[0, -1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
2022119135535 INFO src=drizzlepac.hapmultisequencer- Processing completed at 2022-04-29 13:55:35.523896
2022119135535 INFO src=drizzlepac.hapmultisequencer- Total processing time: 17.952799 sec
2022119135535 INFO src=drizzlepac.hapmultisequencer- Return code for use by calling Condor/OWL workflow code: 0 (zero) for success, non-zero for error or exit. 
2022119135535 INFO src=drizzlepac.hapmultisequencer- Return condition 1
Return Value:  1
```
The files that were created are in 

/ifs/archive/ops/hst/info/owlmgr/repro_sci/hap/skycell-p2489x15y02

No drizzle products were created. The flcs were copied over.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-764?focusedCommentId=584801#comment-584801):_

The problem stems from the logic which assigns exposures to each SkyCell.  This visit includes exposures from both WFC3/IR and WFC3/UVIS.  However, only the UVIS exposures have a large enough footprint to overlap the p2489x15y02 SkyCell, yet all exposures from the visit were identified as overlapping the SkyCell, as seen in the attached figure.  

This logic needs to be revised to insure that each individual exposure gets assigned correctly to the SkyCell it overlaps not just the SkyCells that all the exposures in the visit overlaps.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-764?focusedCommentId=584958#comment-584958):_

[Drizzlepac PR #&#x2060;1360](https://github.com/spacetelescope/drizzlepac/pull/1360) was filed to address the problems described here.  It was tested against this SkyCell's data to verify that the SkyCell can be processed and can generate all the valid layers.
