### ISSUE TITLE
MVM: SkyCell identify fails for data from visit iepo3k

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1359]
_Issue [HLA-765](https://jira.stsci.edu/browse/HLA-765) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

No SkyCell ID was determined for data from visit 'iepo3k' causing problems during pipeline MVM processing as noted in HSTSDP-1780.  

Interactively trying to identify what SkyCell this data overlaps resulted in the following Exception being generated:

> Traceback (most recent call last):
>  File "C:\Users\Warren\miniconda3\envs\rthst38\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
>  exec(code_obj, self.user_global_ns, self.user_ns)
>  File "<ipython-input-114-b4b466ec7059>", line 1, in <module>
>  scids = cutils.get_sky_cells(flcs)
>  File "D:\Drive_D\cygwin\home\Warren Hack\github\drizzlepac\drizzlepac\haputils\cell_utils.py", line 146, in get_sky_cells
>  File "D:\Drive_D\cygwin\home\Warren Hack\github\drizzlepac\drizzlepac\haputils\cell_utils.py", line 761, in get_sky_cells
>  File "D:\Drive_D\cygwin\home\Warren Hack\github\drizzlepac\drizzlepac\haputils\cell_utils.py", line 741, in get_projection_cells
>  if ra is None:
>  File "D:\Drive_D\cygwin\home\Warren Hack\github\drizzlepac\drizzlepac\haputils\cell_utils.py", line 617, in get_edges_sky
>  if len(self.corners) == 0:
>  File "D:\Drive_D\cygwin\home\Warren Hack\github\drizzlepac\drizzlepac\haputils\cell_utils.py", line 598, in find_corners
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

If this Exception was thrown when generating the database entry for exposures from this visit, then no SkyCell ID would have been found and the database would have an entry of 'None'.  At any rate, this problem needs to be resolved so that the data can be placed in the correct SkyCell.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-765?focusedCommentId=584957#comment-584957):_

This problem should be addressed by the changes included in [Drizzlepac PR #&#x2060;1360](https://github.com/spacetelescope/drizzlepac/pull/1360).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-765?focusedCommentId=585125#comment-585125):_

*NOTE:* Fixing this in the pipeline will most likely require trying to assign these exposures to a SkyCell or SkyCells again after the PR has been delivered to operations.
