### ISSUE TITLE
Error due to incompatibility with numpy 1.25

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/drizzlepac#1601]
Hi,

 I recently had a test in another package start failing, and it turns out it's due to an error thrown with the combination of `drizzlepac` and `numpy` version 1.25.0. I assume this is a simple fix in `drizzlepac` to change this comparison, but I don't have time right this moment to do it myself. Here's the traceback:

```
Traceback (most recent call last):
  File "/home/runner/work/slitlessutils/slitlessutils/.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/drizzlepac/util.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "/home/runner/work/slitlessutils/slitlessutils/.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/drizzlepac/astrodrizzle.py", line 223, in run
    createMedian.createMedian(imgObjList, configobj, procSteps=procSteps)
  File "/home/runner/work/slitlessutils/slitlessutils/.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/drizzlepac/createMedian.py", line 99, in createMedian
    _median(imgObjList, paramDict)
  File "/home/runner/work/slitlessutils/slitlessutils/.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/drizzlepac/createMedian.py", line 395, in _median
    result = min_med(
  File "/home/runner/work/slitlessutils/slitlessutils/.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/drizzlepac/minmed.py", line 424, in min_med
    if weight_masks == [] or weight_masks is None:
ValueError: operands could not be broadcast together with shapes (2,61,4297) (0,)
```

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-1043](https://jira.stsci.edu/browse/HLA-1043)._

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-1043?focusedCommentId=685482#comment-685482):_

This issue was addressed by Mihai 029935f (PR#&#x2060;1753).
