### ISSUE TITLE
WFPC2 drizzle error: exitcode: -9

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1666]
_Issue [HLA-1121](https://jira.stsci.edu/browse/HLA-1121) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

*jcn653/HAP_jcn653.err (1 total)*

 

##############################################################################

#                                                                            #

# ERROR:                                                                     #

# AstroDrizzle Version 3.6.2rc1.dev3+g10c73c9 encountered a problem!         #

# Processing terminated at 23:24:39.726 (13/09/2023).                        #

#                                                                            #

##############################################################################

Traceback (most recent call last):

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/util.py", line 230, in wrapper

    result = func(*args, **kwargs)

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/astrodrizzle.py", line 216, in run

    adrizzle.drizSeparate(imgObjList, outwcs, configobj, wcsmap=wcsmap,

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/adrizzle.py", line 359, in drizSeparate

    run_driz(imageObjectList, output_wcs.single_wcs, paramDict, single=True,

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/adrizzle.py", line 696, in run_driz

    mputil.launch_and_wait(subprocs, pool_size)  # blocks till all done

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/stsci/tools/mputil.py", line 103, in launch_and_wait

    raise RuntimeError("Problem during: "+str(p.process.name)+ \

RuntimeError: Problem during: adrizzle.run_driz_img(), exitcode: -9. Check log.

Traceback (most recent call last):

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/runastrodriz.py", line 915, in run_driz

    drizzlepac.astrodrizzle.AstroDrizzle(input=infile, configobj=None,

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/astrodrizzle.py", line 119, in AstroDrizzle

    run(configObj, wcsmap=wcsmap)

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/util.py", line 244, in wrapper

    raise errorobj

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/util.py", line 230, in wrapper

    result = func(*args, **kwargs)

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/astrodrizzle.py", line 216, in run

    adrizzle.drizSeparate(imgObjList, outwcs, configobj, wcsmap=wcsmap,

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/adrizzle.py", line 359, in drizSeparate

    run_driz(imageObjectList, output_wcs.single_wcs, paramDict, single=True,

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/adrizzle.py", line 696, in run_driz

    mputil.launch_and_wait(subprocs, pool_size)  # blocks till all done

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/stsci/tools/mputil.py", line 103, in launch_and_wait

    raise RuntimeError("Problem during: "+str(p.process.name)+ \

RuntimeError: Problem during: adrizzle.run_driz_img(), exitcode: -9. Check log.

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/user/mburger/hap/singlevisits/make_svhap.py", line 137, in <module>

    make_svhap(visit, today, manifest)

  File "/user/mburger/hap/singlevisits/make_svhap.py", line 72, in make_svhap

    runastrodriz.process(asn, debug=True)

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/runastrodriz.py", line 658, in process

    align_aposteriori, aposteriori_table = verify_alignment(_inlist,

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/runastrodriz.py", line 1170, in verify_alignment

    drz, fdicts, ddicts = run_driz(inlist, trlfile, calfiles, mode=tmpmode,

  File "/user/mburger/anaconda3/envs/caldp_2023_2_0/lib/python3.9/site-packages/drizzlepac/runastrodriz.py", line 935, in run_driz

    raise Exception(str(errorobj))

Exception: Problem during: adrizzle.run_driz_img(), exitcode: -9. Check log.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1121?focusedCommentId=669463#comment-669463):_

I was able to run the program (JCN653) through pipeline processing as well as the SVM pipeline without issue.
