### ISSUE TITLE
tweakreg crashes on images from wfc3dash

### ISSUE THREAD

**Issue by kevinluhman** [spacetelescope/drizzlepac#188]
After running `process_raw.run_all()` from https://github.com/gbrammer/wfc3dash by @gbrammer on WFC3 images obtained with the DASH method, I have tried processing the resulting images with tweakreg, but it crashes with the following error:

```
[ERROR   ] An unhandled exception ocurred:
Traceback (most recent call last):
  File "/Users/kll207/anaconda2/envs/iraf27/lib/python2.7/site-packages/drizzlepac/util.py", line 219, in wrapper
    func(*args, **kwargs)
  File "/Users/kll207/anaconda2/envs/iraf27/lib/python2.7/site-packages/drizzlepac/tweakreg.py", line 484, in run
    xycatalog=refimg.xy_catalog, **kwargs)
  File "/Users/kll207/anaconda2/envs/iraf27/lib/python2.7/site-packages/drizzlepac/imgclasses.py", line 1145, in __init__
    self.wcs = utils.output_wcs(wcs_list, undistort=undistort)
  File "/Users/kll207/anaconda2/envs/iraf27/lib/python2.7/site-packages/stwcs/distortion/utils.py", line 44, in output_wcs
    outwcs = make_orthogonal_cd(ref_wcs)
  File "/Users/kll207/anaconda2/envs/iraf27/lib/python2.7/site-packages/stwcs/distortion/utils.py", line 126, in make_orthogonal_cd
    scale = (wcs.idcscale) / 3600.  # HST pixel scale provided
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by mcara** [comment]
This error typically occurs when using images that contain WCS that has not "updated". Tipically, after downloading files (`FLT` or `FLC` kind) from archive, you need to run `stwcs.updatewcs.updatewcs()` on those images. I am not familiar with `wfc3dash` and so I do not know how does it handle WCS conversion (if at all) or what is the correct workflow for using that tool.

Please contact @gbrammer or open an issue at https://github.com/gbrammer/wfc3dash

**Comment by kevinluhman** [comment]
Thanks for your help!

**Comment by mcara** [comment]
@kevinluhman No problem. Did running `updatewcs` on your FLT images solved the issue?

**Comment by kevinluhman** [comment]
Yep, that fixed it. The images were then processed properly by tweakreg.
