### ISSUE TITLE
Fix tweakback WCSBase exception

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzlepac#549]
Help call [INC0149346](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=34aad1f3db0a0458fb50f9baae96192f%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true) reported a problem with 'tweakback' not working for simple-FITS file drizzle products with the following traceback:
`>>> tweakback.tweakback('ngc1300w_acs_f814w_exp_drc_sci.fits')
TweakBack Version 0.4.0(14-Oct-2014) started at: 14:08:35.070 (06/01/2020)

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/lubeda/opt/anaconda3/envs/test2/lib/python3.6/site-packages/drizzlepac/tweakback.py", line 191, in tweakback
orig_wcs = wcsutil.HSTWCS(drzfile,ext=sciext,wcskey=orig_wcskey)
File "/Users/lubeda/opt/anaconda3/envs/test2/lib/python3.6/site-packages/stwcs/wcsutil/hstwcs.py", line 147, in __init__
key=self.wcskey)
File "/Users/lubeda/opt/anaconda3/envs/test2/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 428, in __init__
colsel=colsel, warnings=False)
TypeError: WCSBase.__init__() argument 2 must be str, not None
`

**Comment by stsci-hack** [comment]
It turns out this issue stems from an incorrect default value for the WCSKEY designation when opening the WCS for the drizzle product.  This is not an issue for MEF drizzle products generated with 'build=True' parameter in 'drizzlepac.astrodrizzle.AstroDrizzle'.

**Comment by nden** [comment]
Resolved in #551
