### ISSUE TITLE
SVM: Handle ACS/SBC data which does not contain any astronomical data

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#842]
_Issue [HLA-445](https://jira.stsci.edu/browse/HLA-445) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Processing crashed with the Exception included at the bottom of this discussion for dataset J9QU06.  The traceback is not very illuminating as to the fundamental issue, but the SBC dataset in this instance contains six images, and the resultant drizzled image does not appear to have any astronomical signal in it.  Both the non-illuminated and the background of the illuminated portion of the data are identically zero.  The requires one to be a bit more clever and needing to use the drizzled footprint in order to compute statistics on the image in order to decide the action to pursue for the background determination. 

In order to decide the action to pursue, if greater than 25% of the illuminated portion o the image are identically zero, then set the background to zero and compute the background rms based upon the values of the non-zero pixels.

 

cat results_2020-10-21/j9qu06/HAP_j9qu06.out

Traceback (most recent call last):

  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/hapsequencer.py", line 533, in run_hap_processing

    phot_mode=phot_mode)

  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/hapsequencer.py", line 115, in create_catalog_products

    diagnostic_mode=diagnostic_mode)

  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/catalog_utils.py", line 469, in *_init_*

    maxiters=self.param_dict['maxiters'])

  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/catalog_utils.py", line 219, in compute_background

    maxiters=maxiters)

  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/astropy/stats/sigma_clipping.py", line 756, in sigma_clipped_stats

    mean = np.nanmean(data_clipped, axis=axis)

  File "<*_array_function_* internals>", line 6, in nanmean

  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/numpy/lib/nanfunctions.py", line 952, in nanmean

    avg = _divide_by_count(tot, cnt, out=out)

  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/numpy/lib/nanfunctions.py", line 214, in _divide_by_count

    return np.divide(a, b, out=a, casting='unsafe')

ValueError: output array is read-only

2020295132245 INFO src=drizzlepac.hapsequencer- Processing completed at 2020-10-21 13:22:45.278478

2020295132245 INFO src=drizzlepac.hapsequencer- Total processing time: 157.393494 sec

2020295132245 INFO src=drizzlepac.hapsequencer- Return exit code for use by calling Condor/OWL workflow code: 0 (zero) for success, 1 for error 

2020295132245 INFO src=drizzlepac.hapsequencer- Return condition 1

j9qu06_acs_sbc_vid.html

j9qu06_acs_sbc_point_vid.html

j9qu06_acs_sbc_segment_vid.html

Output status = 1

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-445?focusedCommentId=493795#comment-493795):_

This ticket has been reviewed and merged on Github (PR#&#x2060;846).

**Comment by mdlpstsci** [comment]
As note above this ticket is closed.
